version: '3.5'
services:
  api:
    build: .
    hostname: api
    depends_on:
      - redis
    expose:
      - "5001"
    environment:
      - PORT=5001
      - REDIS_HOSTNAME=redis
    deploy: {
      replicas: 3
    }
    restart: always
  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - api
      ports:
        - "8090:8090"
      container_name: nginx
      restart: always
  redis:
      image: redis:latest
      hostname: redis
      expose:
        - "6379"
      ports:
        - "6379:6379"
      container_name: redis
      restart: always
networks:
  default:
    driver: bridge
    name: motorway